### ISSUE TITLE
jndiDataSource() related error?

### ISSUE THREAD

**Issue by conve** [wilkinsona/spring-boot-sample-tomcat-jndi#2]
When I include your sample jndiDataSource() bean declaration in Application.groovy, I get this error. Any idea what this means?

`ERROR grails.boot.GrailsApp - Application startup failed
org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration$LiquibaseConfiguration': 
Invocation of init method failed; 
nested exception is java.lang.IllegalStateException: 
Cannot find changelog location: 
class path resource [db/changelog/db.changelog-master.yaml] 
(please add changelog or check your Liquibase configuration)`

**Comment by wilkinsona** [comment]
It looks like Spring Boot's auto-configuration for Liquibase is being activated as you have Liquibase on the classpath and a `DataSource` bean. As the exception message suggests, you either need to add a Liquibase changelog or modify your Liquibase configuration.
