### ISSUE TITLE
Fails when adding spring-boot-starter-data-jpa as a dependency

### ISSUE THREAD

**Issue by apixandru** [wilkinsona/spring-boot-sample-tomcat-jndi#4]
As the name suggests, if we just add the dependency to spring-boot-starter-data-jpa, it no longer works.

Is there any workaround?

**Comment by wilkinsona** [comment]
I have no idea. You haven't said which version of the data JPA starter you added  or described how it "no longer works". If you want me to spend some time helping you, please spend some time to provide a reasonable amount of information.

**Comment by apixandru** [comment]
I just submitted a pull request here to illustrate the issue https://github.com/wilkinsona/spring-boot-sample-tomcat-jndi/pull/5

**Comment by wilkinsona** [comment]
Thanks for the example. You're hitting [this problem](http://stackoverflow.com/questions/27822619/howto-use-jndi-database-connection-with-spring-boot-and-spring-data-using-embedd/27825078). You can either work around it as described in the answer or you can upgrade to Spring Boot 1.4 which automatically ensures that JNDI lookups will work during start up.
